scss_files: 'app/styles'

# exclude: 'bower_components/bootstrap-sass/assets/stylesheets/bootstrap/*.scss'

# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
linters:

  BangFormat:
    enabled: true

  BorderZero:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true

  HexLength:
    enabled: true

  HexNotation:
    enabled: true

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true

  Indentation:
    enabled: true

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: false

  NestingDepth:
    enabled: true

  PlaceholderInExtend:
    enabled: true

  # TODO review/enable (it can benefit gzip compression)
  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true

  # TODO review/enable (switch to the CSS3 standard double colon)
  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: true

  SelectorDepth:
    enabled: true

  SelectorFormat:
    enabled: false

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true

  SpaceBetweenParens:
    enabled: true

  StringQuotes:
    enabled: true

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true

  VendorPrefix:
    enabled: true

  ZeroUnit:
    enabled: true
